import os
import subprocess
import asyncio
import sys
from datetime import datetime, time

# Import shared functionality from daily_log.py
# Assuming this script runs from d:\AI 프로젝트\MCP_notion-antigravity\scripts\
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from daily_log import log_update

def get_todays_commits():
    """Fetches git commits from today midnight until now."""
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) # d:\AI 프로젝트
    
    try:
        # Get git log since midnight
        # Requires git to be in PATH
        result = subprocess.run(
            ["git", "log", "--since=midnight", "--pretty=format:- %s (%h)"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            encoding='utf-8' # Force utf-8 for git output
        )
        
        if result.returncode != 0:
            return f"Error fetching git log: {result.stderr}"
            
        logs = result.stdout.strip()
        if not logs:
            return "No code changes detected today."
            
        return logs
    except Exception as e:
        return f"Failed to execute git command: {str(e)}"

async def main():
    print("[INFO] Starting Daily Auto Log...")
    
    # 1. Get Content from Git
    commits = get_todays_commits()
    print(f"[INFO] Commits found:\n{commits}")
    
    # 2. Prepare Log Details
    today_str = datetime.now().strftime("%Y-%m-%d")
    title = f"{today_str} Daily Project Update"
    goal = "Daily Automated Logging"
    
    if "No code changes" in commits:
        achievement = "System Active (No new commits)"
        type_val = "Maintenance"
        priority = "Low"
    else:
        # Count lines for rough metric
        commit_count = commits.count('\n') + 1
        achievement = f"{commit_count} commits recorded"
        type_val = "Log"
        priority = "Medium"
    
    content = f"# 📅 Daily Automation Report\n\n## 📝 Git Commits\n{commits}\n\n## 🤖 Status\n- Auto-generated by Raph Agent\n- Time: {datetime.now().strftime('%H:%M:%S')}"

    # 3. Upload to Notion
    await log_update(title, goal, achievement, content, type_val, priority)

if __name__ == "__main__":
    asyncio.run(main())
