from __future__ import annotations

import argparse
import importlib.util
import json
import secrets
import sys
from pathlib import Path
from typing import Any

GENERATED_FIELDS = (
    "AGRIGUARD_DB_PASSWORD",
    "AGRIGUARD_SECRET_KEY",
    "AGRIGUARD_QR_TOKEN_PEPPER",
)


def _load_peer_module(module_name: str) -> Any:
    script_path = Path(__file__).resolve().with_name(f"{module_name}.py")
    spec = importlib.util.spec_from_file_location(module_name, script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


validate_launch_env_template = _load_peer_module("validate_launch_env_template")
launch_env_preflight = validate_launch_env_template.launch_env_preflight
run_guarded_launch = _load_peer_module("run_guarded_launch")


def _default_app_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _workspace_root(app_root: Path) -> Path:
    if app_root.parent.name == "apps":
        return app_root.parents[1]
    return app_root.parent


def _rel(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path)


def _generated_secret(num_bytes: int = 32) -> str:
    return secrets.token_urlsafe(num_bytes)


def _quote_powershell_arg(value: str) -> str:
    if value and not any(char.isspace() for char in value) and "'" not in value:
        return value
    return "'" + value.replace("'", "''") + "'"


def _format_powershell_command(command: list[str]) -> str:
    return "& " + " ".join(_quote_powershell_arg(str(part)) for part in command)


def _env_lines(env: dict[str, str]) -> list[str]:
    return [
        "# AgriGuard launch operator env",
        "# Generated by prepare_launch_env.py. Keep this file out of git.",
        "",
        f"AGRIGUARD_DB_USER={env['AGRIGUARD_DB_USER']}",
        f"AGRIGUARD_DB_PASSWORD={env['AGRIGUARD_DB_PASSWORD']}",
        f"AGRIGUARD_DB_NAME={env['AGRIGUARD_DB_NAME']}",
        "AGRIGUARD_AUTO_CREATE_SCHEMA=false",
        f"AGRIGUARD_ALLOWED_ORIGINS={env['AGRIGUARD_ALLOWED_ORIGINS']}",
        f"AGRIGUARD_SECRET_KEY={env['AGRIGUARD_SECRET_KEY']}",
        f"AGRIGUARD_QR_TOKEN_PEPPER={env['AGRIGUARD_QR_TOKEN_PEPPER']}",
        f"AGRIGUARD_PUBLIC_VERIFY_BASE_URL={env['AGRIGUARD_PUBLIC_VERIFY_BASE_URL']}",
        f"AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE={env['AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE']}",
        "ALLOW_TEST_BYPASS=false",
        "ALLOW_DEV_AUTH_FALLBACK=false",
        "",
    ]


def build_env(
    *,
    allowed_origins: str,
    public_verify_base_url: str,
    firebase_service_account_file: Path,
    db_user: str = "agriguard",
    db_name: str = "agriguard",
    db_password: str | None = None,
    secret_key: str | None = None,
    qr_token_pepper: str | None = None,
) -> dict[str, str]:
    return {
        "AGRIGUARD_DB_USER": db_user,
        "AGRIGUARD_DB_PASSWORD": db_password or _generated_secret(24),
        "AGRIGUARD_DB_NAME": db_name,
        "AGRIGUARD_AUTO_CREATE_SCHEMA": "false",
        "AGRIGUARD_ALLOWED_ORIGINS": allowed_origins,
        "AGRIGUARD_SECRET_KEY": secret_key or _generated_secret(),
        "AGRIGUARD_QR_TOKEN_PEPPER": qr_token_pepper or _generated_secret(),
        "AGRIGUARD_PUBLIC_VERIFY_BASE_URL": public_verify_base_url,
        "AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE": str(firebase_service_account_file),
        "ALLOW_TEST_BYPASS": "false",
        "ALLOW_DEV_AUTH_FALLBACK": "false",
    }


def write_env(path: Path, env: dict[str, str], *, force: bool = False) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite it")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(_env_lines(env)), encoding="utf-8")


def _redacted_env_summary(env: dict[str, str]) -> list[dict[str, object]]:
    return [
        {
            "key": key,
            "present": bool(value.strip()),
            "sensitive": key in GENERATED_FIELDS or bool(validate_launch_env_template.SENSITIVE_KEY_RE.search(key)),
            "value": "<redacted>",
        }
        for key, value in sorted(env.items())
    ]


def _resolve_firebase_file(value: str, *, app_root: Path) -> Path:
    return launch_env_preflight._resolve_app_relative_path(value, app_root=app_root)  # noqa: SLF001


def _firebase_file_checks(
    env: dict[str, str],
    *,
    allow_missing_firebase_file: bool,
    app_root: Path,
) -> dict[str, object]:
    value = (env.get("AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE") or "").strip()
    if not value:
        return {
            "findings": ["AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE is required."],
            "exists": False,
            "valid": False,
        }

    path = _resolve_firebase_file(value, app_root=app_root)
    exists = path.is_file()
    if allow_missing_firebase_file and not exists:
        return {"findings": [], "exists": False, "valid": False}

    findings, exists = launch_env_preflight._firebase_credentials_file_check(  # noqa: SLF001
        value,
        source="AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE",
        app_root=app_root,
    )
    return {"findings": findings, "exists": exists, "valid": not findings}


def build_report(
    *,
    env_file: Path,
    app_root: Path,
    env: dict[str, str],
    allow_missing_firebase_file: bool = False,
    guarded_output_dir: Path | None = None,
    guarded_output_prefix: str = run_guarded_launch.DEFAULT_OUTPUT_PREFIX,
    guarded_status_json: Path | None = None,
) -> dict[str, object]:
    workspace_root = _workspace_root(app_root)
    guarded_output_dir = (guarded_output_dir or (workspace_root / "var")).resolve()
    guarded_status_json = (
        guarded_status_json.resolve()
        if guarded_status_json is not None
        else (guarded_output_dir / f"{guarded_output_prefix}-status.json").resolve()
    )
    artifact_paths = run_guarded_launch._artifact_paths(guarded_output_dir, guarded_output_prefix)  # noqa: SLF001
    validation = validate_launch_env_template.build_validation_report(env_file=env_file, app_root=app_root)
    firebase_checks = _firebase_file_checks(
        env,
        allow_missing_firebase_file=allow_missing_firebase_file,
        app_root=app_root,
    )
    local_file_findings = firebase_checks["findings"]
    assert isinstance(local_file_findings, list)
    validation_ready = validation.get("ready_for_preflight") is True
    ready_for_preflight = validation_ready and not local_file_findings
    validation_findings = validation.get("blocking_findings")
    blocking_findings = list(validation_findings) if isinstance(validation_findings, list) else []
    blocking_findings.extend(local_file_findings)
    return {
        "schema_version": 1,
        "status": "pass" if ready_for_preflight else "fail",
        "ready_for_preflight": ready_for_preflight,
        "env_file": _rel(env_file, workspace_root),
        "secrets_redacted": True,
        "generated_fields": list(GENERATED_FIELDS),
        "operator_provided_fields": [
            "AGRIGUARD_ALLOWED_ORIGINS",
            "AGRIGUARD_PUBLIC_VERIFY_BASE_URL",
            "AGRIGUARD_FIREBASE_SERVICE_ACCOUNT_FILE",
        ],
        "variables": _redacted_env_summary(env),
        "validation": {
            "placeholder_count": validation.get("placeholder_count"),
            "missing_required_keys": validation.get("missing_required_keys"),
            "forbidden_flags_enabled": validation.get("forbidden_flags_enabled"),
            "blocking_findings": blocking_findings,
        },
        "local_file_checks": {
            "allow_missing_firebase_file": allow_missing_firebase_file,
            "firebase_service_account_file_exists": firebase_checks["exists"],
            "firebase_service_account_file_valid": firebase_checks["valid"],
            "firebase_service_account_file_path": "<redacted>",
        },
        "guarded_output_dir": _rel(guarded_output_dir, workspace_root),
        "guarded_output_prefix": guarded_output_prefix,
        "guarded_status_json": _rel(guarded_status_json, workspace_root),
        "safe_next_commands": [
            _format_powershell_command(
                [
                    sys.executable,
                    str(app_root / "scripts" / "validate_launch_env_template.py"),
                    "--app-root",
                    str(app_root),
                    "--env-file",
                    str(env_file),
                    "--json-out",
                    str(artifact_paths["env_validation_json"]),
                    "--markdown-out",
                    str(artifact_paths["env_validation_markdown"]),
                ]
            ),
            _format_powershell_command(
                [
                    sys.executable,
                    str(app_root / "scripts" / "run_guarded_launch.py"),
                    "--app-root",
                    str(app_root),
                    "--env-file",
                    str(env_file),
                    "--output-dir",
                    str(guarded_output_dir),
                    "--output-prefix",
                    guarded_output_prefix,
                    "--emit-handoff",
                    "--status-json-out",
                    str(guarded_status_json),
                ]
            ),
        ],
    }


def render_markdown(report: dict[str, object]) -> str:
    lines = [
        "# AgriGuard Prepared Launch Env",
        "",
        f"- Status: `{report['status']}`",
        f"- Ready for preflight: `{str(report['ready_for_preflight']).lower()}`",
        f"- Env file: `{report['env_file']}`",
        f"- Secrets redacted: `{str(report['secrets_redacted']).lower()}`",
        "",
        "## Generated Fields",
        "",
    ]
    lines.extend(f"- `{field}`" for field in report.get("generated_fields", []))
    lines.extend(["", "## Operator Provided Fields", ""])
    lines.extend(f"- `{field}`" for field in report.get("operator_provided_fields", []))
    lines.extend(["", "## Validation Findings", ""])
    findings = (
        report.get("validation", {}).get("blocking_findings")
        if isinstance(report.get("validation"), dict)
        else None
    )
    if isinstance(findings, list) and findings:
        lines.extend(f"- `{finding}`" for finding in findings)
    else:
        lines.append("No shape-only blockers were found.")
    lines.extend(["", "## Next Commands", ""])
    lines.extend(f"- `{command}`" for command in report.get("safe_next_commands", []))
    lines.append("")
    return "\n".join(lines)


def write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    app_root = _default_app_root()
    workspace_root = _workspace_root(app_root)
    parser = argparse.ArgumentParser(
        description="Prepare an AgriGuard launch env file with generated local secrets and operator-provided public values."
    )
    parser.add_argument("--app-root", type=Path, default=app_root)
    parser.add_argument("--out", type=Path, default=workspace_root / "var" / "agriguard-launch-operator.env")
    parser.add_argument("--allowed-origins", required=True)
    parser.add_argument("--public-verify-base-url", required=True)
    parser.add_argument("--firebase-service-account-file", type=Path, required=True)
    parser.add_argument("--db-user", default="agriguard")
    parser.add_argument("--db-name", default="agriguard")
    parser.add_argument("--db-password", default=None)
    parser.add_argument("--secret-key", default=None)
    parser.add_argument("--qr-token-pepper", default=None)
    parser.add_argument(
        "--allow-missing-firebase-file",
        action="store_true",
        help="Permit report generation before the Firebase service account JSON exists on this host.",
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--json-out", type=Path, default=None)
    parser.add_argument("--markdown-out", type=Path, default=None)
    parser.add_argument(
        "--guarded-output-dir",
        type=Path,
        default=None,
        help="Guarded-launch output directory to embed in safe next commands. Defaults to workspace var/.",
    )
    parser.add_argument(
        "--guarded-output-prefix",
        default=run_guarded_launch.DEFAULT_OUTPUT_PREFIX,
        help="Guarded-launch output prefix to embed in safe next commands.",
    )
    parser.add_argument(
        "--guarded-status-json",
        type=Path,
        default=None,
        help="Guarded-launch status JSON path to embed in safe next commands.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    app_root = args.app_root.resolve()
    env_file = args.out.resolve()
    env = build_env(
        allowed_origins=args.allowed_origins,
        public_verify_base_url=args.public_verify_base_url,
        firebase_service_account_file=args.firebase_service_account_file,
        db_user=args.db_user,
        db_name=args.db_name,
        db_password=args.db_password,
        secret_key=args.secret_key,
        qr_token_pepper=args.qr_token_pepper,
    )
    try:
        write_env(env_file, env, force=args.force)
    except FileExistsError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    report = build_report(
        env_file=env_file,
        app_root=app_root,
        env=env,
        allow_missing_firebase_file=args.allow_missing_firebase_file,
        guarded_output_dir=args.guarded_output_dir.resolve() if args.guarded_output_dir else None,
        guarded_output_prefix=args.guarded_output_prefix,
        guarded_status_json=args.guarded_status_json.resolve() if args.guarded_status_json else None,
    )
    if args.json_out is not None:
        write_json(args.json_out.resolve(), report)
    if args.markdown_out is not None:
        args.markdown_out.resolve().parent.mkdir(parents=True, exist_ok=True)
        args.markdown_out.resolve().write_text(render_markdown(report), encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["ready_for_preflight"] is True else 1


if __name__ == "__main__":
    raise SystemExit(main())
