/* global describe, it, expect, vi, beforeEach, afterEach */
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import SensorDeviceManager from './SensorDeviceManager';
import {
  sensorDeviceAdminApi,
  getOperatorToken,
  setOperatorToken,
} from '../services/api';

vi.mock('../services/api', () => ({
  getOperatorToken: vi.fn(),
  setOperatorToken: vi.fn(),
  sensorDeviceAdminApi: {
    list: vi.fn(),
    listUnsupportedIdentities: vi.fn(),
    disableUnsupportedIdentities: vi.fn(),
    reissueUnsupportedIdentity: vi.fn(),
    getBrokerProvisioning: vi.fn(),
    getBrokerProvisioningEvidence: vi.fn(),
    getBrokerProvisioningEvidenceHistory: vi.fn(),
    recordBrokerProvisioningEvidence: vi.fn(),
    listMqttRejections: vi.fn(),
    upsert: vi.fn(),
    disable: vi.fn(),
    reactivate: vi.fn(),
  },
}));

const sensorListResponse = {
  status: 'success',
  items: [
    {
      sensor_id: 'sensor-cold-1',
      label: 'Dock probe 1',
      zone: 'Dock A',
      expected_interval_minutes: 5,
      owner_id: 'tenant-cold-chain',
      is_active: true,
      registered_at: '2026-06-01T00:00:00Z',
      first_seen_at: '2026-06-01T00:00:00Z',
      last_seen_at: '2026-06-09T00:05:00Z',
      last_battery: 91,
      last_status: 'normal',
      updated_at: '2026-06-09T00:05:00Z',
    },
    {
      sensor_id: 'sensor-disabled-1',
      label: 'Shelf probe 1',
      zone: 'Retail Hold',
      expected_interval_minutes: 10,
      owner_id: 'tenant-retail',
      is_active: false,
      registered_at: '2026-06-01T00:00:00Z',
      first_seen_at: null,
      last_seen_at: null,
      last_battery: null,
      last_status: null,
      updated_at: '2026-06-08T00:00:00Z',
    },
  ],
  total: 2,
  active_count: 1,
  disabled_count: 1,
  page: 1,
  page_size: 20,
  total_pages: 1,
};

const mqttRejectionResponse = {
  status: 'success',
  items: [
    {
      id: 'event-mqtt-reject-1',
      sensor_id: 'unknown-mqtt-1',
      reason: 'unregistered_sensor',
      occurred_at: '2026-06-09T01:02:00Z',
      error_message: 'MQTT reading rejected: unregistered_sensor',
      registry_required: true,
    },
  ],
  total: 1,
  reason_counts: {
    unregistered_sensor: 1,
  },
  window_hours: 24,
  page: 1,
  page_size: 10,
  total_pages: 1,
};

const unsupportedIdentityResponse = {
  status: 'success',
  items: [
    {
      sensor_id: 'sensor/unsupported',
      label: 'Legacy slash probe',
      zone: 'Dock C',
      expected_interval_minutes: 5,
      owner_id: 'tenant-legacy',
      is_active: true,
      registered_at: '2026-06-01T00:00:00Z',
      first_seen_at: null,
      last_seen_at: null,
      last_battery: null,
      last_status: null,
      updated_at: '2026-06-09T00:05:00Z',
    },
  ],
  total: 1,
  active_count: 1,
  disabled_count: 0,
  safe_pattern: '[A-Za-z0-9_.:-]+',
  notes: ['Disable active unsupported sensors, reissue a broker-safe sensor ID, then rotate broker credentials.'],
};

const brokerProvisioningResponse = {
  status: 'success',
  generated_at: '2026-06-09T00:10:00Z',
  active_sensor_count: 1,
  disabled_sensor_count: 1,
  unsupported_sensor_ids: ['sensor/unsupported'],
  acl_file: [
    '# Generated by AgriGuard from active sensor_devices.',
    '# MQTT username must match sensor_id.',
    '# Disabled or unsupported sensors are intentionally omitted.',
    '',
    'user sensor-cold-1',
    'topic write agriguard/sensors/sensor-cold-1',
    'topic read agriguard/alerts',
    '',
  ].join('\n'),
  password_file_commands: ['mosquitto_passwd /etc/mosquitto/passwd sensor-cold-1'],
  password_file_delete_commands: ['mosquitto_passwd -D /etc/mosquitto/passwd sensor-disabled-1'],
  dynamic_security_commands: [
    'mosquitto_ctrl <connection options> dynsec createClient sensor-cold-1',
    'mosquitto_ctrl <connection options> dynsec setClientPassword sensor-cold-1',
  ],
  notes: ['mosquitto_passwd commands are interactive by design.'],
};

const brokerProvisioningEvidenceResponse = {
  status: 'success',
  latest: null,
};

const recordedBrokerProvisioningEvidenceResponse = {
  status: 'success',
  latest: {
    id: 'evidence-1',
    recorded_at: '2026-06-09T00:12:00Z',
    applied_at: '2026-06-09T00:12:00Z',
    mode: 'combined',
    artifact_hash: 'ab'.repeat(32),
    artifact_generated_at: '2026-06-09T00:10:00Z',
    broker_host: 'mosquitto-prod-01',
    runbook_reference: 'CHG-2026-0610',
    active_sensor_count: 1,
    disabled_sensor_count: 1,
    unsupported_sensor_count: 1,
    credential_rotation_required: false,
    actor_uid: 'sensor-operator-id',
    actor_email: 'sensor-operator@example.com',
    rotation_note: 'Applied with broker credential rotation.',
  },
};

const brokerProvisioningEvidenceHistoryResponse = {
  status: 'success',
  items: [],
  total: 0,
  broker_host: null,
  page: 1,
  page_size: 5,
  total_pages: 1,
};

const filteredBrokerProvisioningEvidenceHistoryResponse = {
  status: 'success',
  items: [
    {
      id: 'evidence-history-1',
      recorded_at: '2026-06-09T00:14:00Z',
      applied_at: '2026-06-09T00:13:00Z',
      mode: 'combined',
      artifact_hash: 'cd'.repeat(32),
      artifact_generated_at: '2026-06-09T00:10:00Z',
      broker_host: 'mosquitto-prod-01',
      runbook_reference: 'RUNBOOK-HIST',
      active_sensor_count: 1,
      disabled_sensor_count: 1,
      unsupported_sensor_count: 1,
      credential_rotation_required: false,
      actor_uid: 'sensor-operator-id',
      actor_email: 'sensor-operator@example.com',
      rotation_note: 'Applied by ops.',
    },
  ],
  total: 1,
  broker_host: 'mosquitto-prod-01',
  page: 1,
  page_size: 5,
  total_pages: 1,
};

describe('SensorDeviceManager', () => {
  beforeEach(() => {
    Object.defineProperty(globalThis, 'crypto', {
      value: {
        subtle: {
          digest: vi.fn().mockResolvedValue(new Uint8Array(32).fill(0xab).buffer),
        },
      },
      configurable: true,
    });
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText: vi.fn().mockResolvedValue(undefined) },
      configurable: true,
    });
    getOperatorToken.mockReturnValue('operator-token');
    sensorDeviceAdminApi.list.mockResolvedValue({ data: sensorListResponse });
    sensorDeviceAdminApi.listUnsupportedIdentities.mockResolvedValue({ data: unsupportedIdentityResponse });
    sensorDeviceAdminApi.disableUnsupportedIdentities.mockResolvedValue({
      data: {
        status: 'success',
        disabled_count: 1,
        disabled_sensor_ids: ['sensor/unsupported'],
        skipped_sensor_ids: [],
        items: [{ ...unsupportedIdentityResponse.items[0], is_active: false }],
      },
    });
    sensorDeviceAdminApi.reissueUnsupportedIdentity.mockResolvedValue({
      data: {
        status: 'success',
        source_sensor: { ...unsupportedIdentityResponse.items[0], is_active: false },
        replacement_sensor: {
          ...unsupportedIdentityResponse.items[0],
          sensor_id: 'sensor-unsupported-01',
          is_active: true,
          first_seen_at: null,
          last_seen_at: null,
          last_battery: null,
          last_status: null,
        },
        broker_rotation_required: true,
        notes: ['Rotate broker credentials for the replacement sensor ID before returning the physical device to service.'],
      },
    });
    sensorDeviceAdminApi.getBrokerProvisioning.mockResolvedValue({ data: brokerProvisioningResponse });
    sensorDeviceAdminApi.getBrokerProvisioningEvidence.mockResolvedValue({ data: brokerProvisioningEvidenceResponse });
    sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory.mockResolvedValue({
      data: brokerProvisioningEvidenceHistoryResponse,
    });
    sensorDeviceAdminApi.recordBrokerProvisioningEvidence.mockResolvedValue({
      data: recordedBrokerProvisioningEvidenceResponse,
    });
    sensorDeviceAdminApi.listMqttRejections.mockResolvedValue({ data: mqttRejectionResponse });
    sensorDeviceAdminApi.upsert.mockResolvedValue({
      data: {
        status: 'success',
        sensor: {
          ...sensorListResponse.items[0],
          sensor_id: 'packhouse-probe-01',
          label: 'Packhouse probe 01',
          zone: 'Packhouse',
          owner_id: 'tenant-packhouse',
        },
      },
    });
    sensorDeviceAdminApi.disable.mockResolvedValue({
      data: {
        status: 'success',
        sensor: { ...sensorListResponse.items[0], is_active: false },
      },
    });
    sensorDeviceAdminApi.reactivate.mockResolvedValue({
      data: {
        status: 'success',
        sensor: { ...sensorListResponse.items[1], is_active: true },
      },
    });
  });

  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it('loads registered sensors and renders state summaries', async () => {
    render(<SensorDeviceManager />);

    expect(screen.getByTestId('sensor-device-heading')).toHaveClass('text-2xl');
    expect(screen.getByTestId('sensor-device-heading')).toHaveClass('sm:text-3xl');
    expect(await screen.findByText('sensor-cold-1')).toBeInTheDocument();
    expect(sensorDeviceAdminApi.list).toHaveBeenCalledWith({
      sensorStatus: 'all',
      zone: '',
      page: 1,
      pageSize: 20,
    });
    expect(screen.getAllByText('Active').length).toBeGreaterThan(0);
    expect(screen.getAllByText('Disabled').length).toBeGreaterThan(0);
    expect(screen.getByText('Showing 2 of 2 matching sensors')).toBeInTheDocument();
    expect(screen.getByText('tenant-cold-chain')).toBeInTheDocument();
    expect(screen.getByText('tenant-retail')).toBeInTheDocument();
    expect(screen.getByText('91%')).toBeInTheDocument();
    await waitFor(() => {
      expect(screen.getAllByText('sensor/unsupported').length).toBeGreaterThan(0);
    });
    expect(sensorDeviceAdminApi.listUnsupportedIdentities).toHaveBeenCalledTimes(1);
    expect(await screen.findByText(/user sensor-cold-1/)).toBeInTheDocument();
    expect(sensorDeviceAdminApi.getBrokerProvisioning).toHaveBeenCalledWith({
      passwordFilePath: '/etc/mosquitto/passwd',
      dynamicSecurityRole: 'agriguard-sensor',
    });
    expect(sensorDeviceAdminApi.getBrokerProvisioningEvidence).toHaveBeenCalledTimes(1);
    expect(sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory).toHaveBeenCalledWith({
      brokerHost: '',
      page: 1,
      pageSize: 5,
    });
    expect(screen.getByText('No evidence recorded')).toBeInTheDocument();
    expect(screen.getByText('No broker provisioning evidence history found.')).toBeInTheDocument();
    expect(await screen.findByText('unknown-mqtt-1')).toBeInTheDocument();
    expect(screen.getByText('1 rejected attempts in the last 24 hours')).toBeInTheDocument();
  });

  it('keeps the mobile sensor controls compact above the registry summary', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');

    const tokenControls = screen.getByLabelText('Operator bearer token').parentElement;
    expect(screen.getByTestId('sensor-operator-token-card')).toHaveClass('w-full');
    expect(tokenControls).toHaveClass('grid');
    expect(tokenControls).toHaveClass('grid-cols-[minmax(0,1fr)_5rem]');

    const filterForm = screen.getByTestId('sensor-filter-panel').querySelector('form');
    expect(filterForm).toHaveClass('grid-cols-2');
    expect(screen.getByRole('button', { name: /apply filters/i })).toHaveClass('col-span-2');
    expect(screen.getByRole('button', { name: /apply filters/i })).toHaveClass('lg:col-span-1');

    expect(screen.getByTestId('sensor-stat-grid')).toHaveClass('grid-cols-3');
  });

  it('does not auto-load protected sensor data without an operator token', async () => {
    getOperatorToken.mockReturnValue('');

    render(<SensorDeviceManager />);

    expect(await screen.findByText('Save an operator bearer token to load protected sensor data.')).toBeInTheDocument();
    expect(sensorDeviceAdminApi.list).not.toHaveBeenCalled();
    expect(sensorDeviceAdminApi.listUnsupportedIdentities).not.toHaveBeenCalled();
    expect(sensorDeviceAdminApi.getBrokerProvisioning).not.toHaveBeenCalled();
    expect(sensorDeviceAdminApi.getBrokerProvisioningEvidence).not.toHaveBeenCalled();
    expect(sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory).not.toHaveBeenCalled();
    expect(sensorDeviceAdminApi.listMqttRejections).not.toHaveBeenCalled();
  });

  it('renders registered sensor rows as mobile-first action cards', async () => {
    render(<SensorDeviceManager />);

    expect(await screen.findByText('sensor-cold-1')).toBeInTheDocument();

    const table = screen.getByTestId('registered-sensors-table');
    expect(table).not.toHaveClass('min-w-[940px]');
    expect(table).toHaveClass('md:min-w-[940px]');

    const rows = screen.getAllByTestId('registered-sensor-row');
    expect(rows[0]).toHaveClass('block');
    expect(rows[0]).toHaveClass('md:table-row');
    expect(within(rows[0]).getByText('Actions')).toBeInTheDocument();
    expect(within(rows[0]).getByRole('button', { name: /edit/i })).toBeInTheDocument();
    expect(within(rows[0]).getByRole('button', { name: /disable/i })).toBeInTheDocument();
  });

  it('saves an operator token for protected sensor API calls', () => {
    getOperatorToken.mockReturnValue('');

    render(<SensorDeviceManager />);

    expect(screen.getByText('No token saved. Protected actions will return 401.')).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Operator bearer token'), { target: { value: 'saved-token' } });
    fireEvent.click(screen.getByRole('button', { name: 'Save' }));

    expect(setOperatorToken).toHaveBeenCalledWith('saved-token');
    expect(screen.getByText('Operator token saved for this browser.')).toBeInTheDocument();
  });

  it('applies state and zone filters to the registry query', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.change(screen.getByLabelText('Sensor state'), { target: { value: 'disabled' } });
    fireEvent.change(screen.getByLabelText('Zone filter'), { target: { value: 'Retail Hold' } });
    fireEvent.click(screen.getByRole('button', { name: /apply filters/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.list).toHaveBeenLastCalledWith({
        sensorStatus: 'disabled',
        zone: 'Retail Hold',
        page: 1,
        pageSize: 20,
      });
    });
  });

  it('applies MQTT rejection audit filters', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('unknown-mqtt-1');
    fireEvent.change(screen.getByLabelText('Window hours'), { target: { value: '48' } });
    fireEvent.change(screen.getByLabelText('Audit sensor ID'), {
      target: { value: 'unknown-mqtt-1' },
    });
    fireEvent.change(screen.getByLabelText('Reason'), { target: { value: 'unregistered_sensor' } });
    fireEvent.click(screen.getByRole('button', { name: /filter audit/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.listMqttRejections).toHaveBeenLastCalledWith({
        windowHours: 48,
        sensorId: 'unknown-mqtt-1',
        reason: 'unregistered_sensor',
        page: 1,
        pageSize: 10,
      });
    });
  });

  it('registers a sensor and refreshes the list', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.change(screen.getByLabelText('Sensor ID'), { target: { value: 'packhouse-probe-01' } });
    fireEvent.change(screen.getByLabelText('Label'), { target: { value: 'Packhouse probe 01' } });
    fireEvent.change(screen.getByLabelText('Assigned zone'), { target: { value: 'Packhouse' } });
    fireEvent.change(screen.getByLabelText('Owner ID'), { target: { value: 'tenant-packhouse' } });
    fireEvent.change(screen.getByLabelText('Expected interval minutes'), { target: { value: '5' } });
    fireEvent.click(screen.getByRole('button', { name: /register sensor/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.upsert).toHaveBeenCalledWith('packhouse-probe-01', {
        label: 'Packhouse probe 01',
        zone: 'Packhouse',
        ownerId: 'tenant-packhouse',
        clearOwner: false,
        expectedIntervalMinutes: '5',
        isActive: true,
      });
    });
    expect(screen.getByRole('status')).toHaveTextContent('Sensor packhouse-probe-01 saved.');
    expect(sensorDeviceAdminApi.list).toHaveBeenCalledTimes(2);
  });

  it('blocks broker-unsafe sensor IDs before saving', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.change(screen.getByLabelText('Sensor ID'), { target: { value: 'bad/sensor' } });
    fireEvent.click(screen.getByRole('button', { name: /register sensor/i }));

    expect(screen.getByRole('status')).toHaveTextContent(
      'Sensor ID may contain letters, numbers, dot, underscore, colon, and hyphen.',
    );
    expect(sensorDeviceAdminApi.upsert).not.toHaveBeenCalled();
  });

  it('disables active unsupported broker identities from the cleanup panel', async () => {
    render(<SensorDeviceManager />);

    await waitFor(() => {
      expect(screen.getAllByText('sensor/unsupported').length).toBeGreaterThan(0);
    });
    fireEvent.click(screen.getByRole('button', { name: /disable active unsupported ids/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.disableUnsupportedIdentities).toHaveBeenCalledTimes(1);
    });
    expect(sensorDeviceAdminApi.disableUnsupportedIdentities.mock.calls[0]).toEqual([]);
    expect(screen.getByRole('status')).toHaveTextContent('1 unsupported sensor ID disabled.');
    expect(sensorDeviceAdminApi.list).toHaveBeenCalledTimes(2);
    expect(sensorDeviceAdminApi.listUnsupportedIdentities).toHaveBeenCalledTimes(2);
  });

  it('reissues an unsupported broker identity as a safe replacement sensor ID', async () => {
    render(<SensorDeviceManager />);

    await waitFor(() => {
      expect(screen.getAllByText('sensor/unsupported').length).toBeGreaterThan(0);
    });

    fireEvent.change(screen.getByLabelText('New broker-safe ID for sensor/unsupported'), {
      target: { value: 'sensor-unsupported-01' },
    });
    fireEvent.click(screen.getByRole('button', { name: /reissue id/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.reissueUnsupportedIdentity).toHaveBeenCalledWith({
        oldSensorId: 'sensor/unsupported',
        newSensorId: 'sensor-unsupported-01',
      });
    });
    expect(screen.getByRole('status')).toHaveTextContent(
      'Sensor sensor/unsupported reissued as sensor-unsupported-01. Rotate broker credentials.',
    );
    expect(sensorDeviceAdminApi.list).toHaveBeenCalledTimes(2);
    expect(sensorDeviceAdminApi.listUnsupportedIdentities).toHaveBeenCalledTimes(2);
    expect(sensorDeviceAdminApi.getBrokerProvisioning).toHaveBeenCalledTimes(2);
  });

  it('blocks unsafe replacement IDs before calling the reissue API', async () => {
    render(<SensorDeviceManager />);

    await waitFor(() => {
      expect(screen.getAllByText('sensor/unsupported').length).toBeGreaterThan(0);
    });
    fireEvent.change(screen.getByLabelText('New broker-safe ID for sensor/unsupported'), {
      target: { value: 'bad/sensor' },
    });
    fireEvent.click(screen.getByRole('button', { name: /reissue id/i }));

    expect(screen.getByRole('status')).toHaveTextContent(
      'Sensor ID may contain letters, numbers, dot, underscore, colon, and hyphen.',
    );
    expect(sensorDeviceAdminApi.reissueUnsupportedIdentity).not.toHaveBeenCalled();
  });

  it('generates, displays, and copies broker provisioning artifacts', async () => {
    render(<SensorDeviceManager />);

    expect(await screen.findByText('MQTT broker provisioning')).toBeInTheDocument();
    expect(screen.getByText('1 active / 1 disabled broker-safe sensors')).toBeInTheDocument();
    expect(screen.getByText(/mosquitto_passwd \/etc\/mosquitto\/passwd sensor-cold-1/)).toBeInTheDocument();
    expect(screen.getByText(/mosquitto_ctrl <connection options> dynsec createClient sensor-cold-1/)).toBeInTheDocument();

    fireEvent.change(screen.getByLabelText('Password file path'), {
      target: { value: '/var/lib/mosquitto/passwd' },
    });
    fireEvent.change(screen.getByLabelText('Dynamic role'), {
      target: { value: 'agriguard.sensor' },
    });
    fireEvent.click(screen.getByRole('button', { name: /^generate$/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.getBrokerProvisioning).toHaveBeenLastCalledWith({
        passwordFilePath: '/var/lib/mosquitto/passwd',
        dynamicSecurityRole: 'agriguard.sensor',
      });
    });

    fireEvent.click(screen.getAllByRole('button', { name: /^copy$/i })[0]);
    await waitFor(() => {
      expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining('user sensor-cold-1'));
    });
    expect(screen.getByRole('status')).toHaveTextContent('ACL file copied.');
  });

  it('records broker provisioning evidence without posting command text or secrets', async () => {
    render(<SensorDeviceManager />);

    expect(await screen.findByText('MQTT broker provisioning')).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Broker host'), {
      target: { value: 'mosquitto-prod-01' },
    });
    fireEvent.change(screen.getByLabelText('Runbook or change reference'), {
      target: { value: 'CHG-2026-0610' },
    });
    fireEvent.change(screen.getByLabelText('Evidence note, no secrets'), {
      target: { value: 'Applied with broker credential rotation.' },
    });
    fireEvent.click(screen.getByRole('button', { name: /record applied evidence/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.recordBrokerProvisioningEvidence).toHaveBeenCalledTimes(1);
    });
    expect(sensorDeviceAdminApi.recordBrokerProvisioningEvidence).toHaveBeenCalledWith({
      mode: 'combined',
      artifactHash: 'ab'.repeat(32),
      artifactGeneratedAt: '2026-06-09T00:10:00Z',
      appliedAt: expect.any(String),
      brokerHost: 'mosquitto-prod-01',
      runbookReference: 'CHG-2026-0610',
      activeSensorCount: 1,
      disabledSensorCount: 1,
      unsupportedSensorCount: 1,
      credentialRotationRequired: false,
      rotationNote: 'Applied with broker credential rotation.',
    });
    const postedPayload = JSON.stringify(sensorDeviceAdminApi.recordBrokerProvisioningEvidence.mock.calls[0][0]);
    expect(postedPayload).not.toContain('mosquitto_passwd');
    expect(postedPayload).not.toContain('setClientPassword');
    expect(screen.getByRole('status')).toHaveTextContent('Broker provisioning evidence recorded.');
    expect(screen.getByText('Credential rotation recorded')).toBeInTheDocument();
    expect(screen.getByText('abababababab')).toBeInTheDocument();
    expect(screen.getByText('mosquitto-prod-01')).toBeInTheDocument();
    expect(screen.getByText('CHG-2026-0610')).toBeInTheDocument();
  });

  it('filters broker provisioning evidence history by broker host', async () => {
    render(<SensorDeviceManager />);

    await waitFor(() => {
      expect(sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory).toHaveBeenCalledTimes(1);
    });
    sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory.mockResolvedValueOnce({
      data: filteredBrokerProvisioningEvidenceHistoryResponse,
    });

    fireEvent.change(screen.getByLabelText('Broker host filter'), {
      target: { value: 'mosquitto-prod-01' },
    });
    fireEvent.click(screen.getByRole('button', { name: /filter history/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.getBrokerProvisioningEvidenceHistory).toHaveBeenLastCalledWith({
        brokerHost: 'mosquitto-prod-01',
        page: 1,
        pageSize: 5,
      });
    });
    expect(await screen.findByText('RUNBOOK-HIST')).toBeInTheDocument();
    expect(screen.getByText('cdcdcdcdcdcd')).toBeInTheDocument();
    expect(screen.getByText('1 recorded broker application events')).toBeInTheDocument();
  });

  it('fills the form from an existing sensor and saves updates', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.click(screen.getAllByRole('button', { name: /edit/i })[0]);

    expect(screen.getByLabelText('Sensor ID')).toHaveValue('sensor-cold-1');
    expect(screen.getByLabelText('Label')).toHaveValue('Dock probe 1');
    expect(screen.getByLabelText('Owner ID')).toHaveValue('tenant-cold-chain');
    fireEvent.change(screen.getByLabelText('Label'), { target: { value: 'Dock probe 1A' } });
    fireEvent.click(screen.getByRole('button', { name: /save sensor/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.upsert).toHaveBeenCalledWith('sensor-cold-1', {
        label: 'Dock probe 1A',
        zone: 'Dock A',
        ownerId: 'tenant-cold-chain',
        clearOwner: false,
        expectedIntervalMinutes: '5',
        isActive: true,
      });
    });
  });

  it('submits an explicit clear-owner intent', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.click(screen.getAllByRole('button', { name: /edit/i })[0]);
    fireEvent.click(screen.getByLabelText(/clear owner/i));
    fireEvent.click(screen.getByRole('button', { name: /save sensor/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.upsert).toHaveBeenCalledWith('sensor-cold-1', {
        label: 'Dock probe 1',
        zone: 'Dock A',
        ownerId: '',
        clearOwner: true,
        expectedIntervalMinutes: '5',
        isActive: true,
      });
    });
    expect(screen.getByLabelText('Owner ID')).toBeDisabled();
  });

  it('disables and reactivates sensors from the table actions', async () => {
    render(<SensorDeviceManager />);

    await screen.findByText('sensor-cold-1');
    fireEvent.click(screen.getByRole('button', { name: /^disable$/i }));

    await waitFor(() => {
      expect(sensorDeviceAdminApi.disable).toHaveBeenCalledWith('sensor-cold-1');
    });
    expect(screen.getByRole('status')).toHaveTextContent('Sensor sensor-cold-1 disabled.');

    fireEvent.click(screen.getByRole('button', { name: /reactivate/i }));
    await waitFor(() => {
      expect(sensorDeviceAdminApi.reactivate).toHaveBeenCalledWith('sensor-disabled-1');
    });
  });

  it('announces load errors through the status region', async () => {
    sensorDeviceAdminApi.list.mockRejectedValue({
      response: { data: { detail: 'Sensor device administration requires an operator role.' } },
    });

    render(<SensorDeviceManager />);

    expect(await screen.findByRole('status')).toHaveTextContent(
      'Sensor device administration requires an operator role.',
    );
  });
});
