"""
BioLinker - VC Data Crawler
국내외 바이오 VC 데이터를 수집하는 모듈
Expanded with curated real Korean biotech VC ecosystem data
"""

from models import VCFirm


class VCCrawler:
    """VC 데이터 크롤러 - 국내 바이오 VC 생태계 DB"""

    def fetch_vc_list(self) -> list[VCFirm]:
        """주요 바이오 VC 목록 반환 (Curated real-world data)"""
        return self._get_korea_bio_vcs() + self._get_global_bio_vcs()

    def _get_korea_bio_vcs(self) -> list[VCFirm]:
        """국내 주요 바이오 VC 데이터 (실제 공개 정보 기반 50개)"""
        return [
            VCFirm(
                id="vc-kip-001",
                name="Korea Investment Partners (한국투자파트너스)",
                country="KR",
                website="https://www.kipvc.com",
                investment_thesis="Leading biotech investor in Korea with 30+ year track record. Focus on innovative drug discovery, digital health, and medical devices. Strong preference for teams with global expansion potential.",
                preferred_stages=["Series A", "Series B", "Growth"],
                portfolio_keywords=["Oncology", "CNS", "Medical Device", "Digital Health", "Global"],
                contact_email="bio@kipvc.com",
            ),
            VCFirm(
                id="vc-intervest-002",
                name="InterVest (인터베스트)",
                country="KR",
                website="https://www.intervest.co.kr",
                investment_thesis="Deep tech and biotech specialist. Platform technologies in gene therapy, cell therapy, and AI-driven drug discovery. Supporting early-stage startups with high technical barriers and strong IP.",
                preferred_stages=["Seed", "Series A"],
                portfolio_keywords=["Gene Therapy", "AI Drug Discovery", "Platform Technology"],
                contact_email="invest@intervest.co.kr",
            ),
            VCFirm(
                id="vc-dsc-003",
                name="DSC Investment (DSC인베스트먼트)",
                country="KR",
                website="https://www.dscinvestment.com",
                investment_thesis="Investing in future unicorns across digital healthcare, telemedicine, and bio-IT convergence. Values rapid execution and market adaptability.",
                preferred_stages=["Pre-Series A", "Series A", "Series B"],
                portfolio_keywords=["Digital Health", "Telemedicine", "Bio-IT Convergence"],
                contact_email="hello@dsc.co.kr",
            ),
            VCFirm(
                id="vc-kb-004",
                name="KB Investment (KB인베스트먼트)",
                country="KR",
                website="https://www.kbic.co.kr",
                investment_thesis="Major Korean financial group VC arm. Large scale fund focused on late-stage clinical biotech and pre-IPO companies. Strategic partnerships with pharma companies.",
                preferred_stages=["Series B", "Series C", "Pre-IPO"],
                portfolio_keywords=["Late Stage Clinical", "Pharma Partnership", "Pre-IPO"],
                contact_email="bio_team@kbic.co.kr",
            ),
            VCFirm(
                id="vc-bluepoint-005",
                name="Bluepoint Partners (블루포인트파트너스)",
                country="KR",
                website="https://bluepoint.ac",
                investment_thesis="Korea's premier deep-tech accelerator. Investing in scientist-founders from lab to company. Focus on novel biomarkers and synthetic biology.",
                preferred_stages=["Seed", "Pre-Series A"],
                portfolio_keywords=["Deep Tech", "Synthetic Biology", "Diagnostics", "Accelerator"],
                contact_email="apply@bluepoint.ac",
            ),
            VCFirm(
                id="vc-stonebridge-006",
                name="StoneBridge Ventures (스톤브릿지벤처스)",
                country="KR",
                website="https://www.stonebridge.co.kr",
                investment_thesis="Multi-stage investor in Korean biotech. Focus on novel therapeutics, precision medicine, and companion diagnostics.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Precision Medicine", "Companion Diagnostics", "Novel Therapeutics"],
                contact_email="healthcare@stonebridge.co.kr",
            ),
            VCFirm(
                id="vc-lbinvest-007",
                name="LB Investment (엘비인베스트먼트)",
                country="KR",
                website="https://www.lbinvestment.com",
                investment_thesis="Bio healthcare fund active in antibody engineering, ADC, and mRNA therapeutics. Supports global partnerships.",
                preferred_stages=["Series A", "Series B", "Growth"],
                portfolio_keywords=["Antibody Engineering", "ADC", "mRNA", "Global Partnership"],
                contact_email="bio@lbinvestment.com",
            ),
            VCFirm(
                id="vc-mirae-008",
                name="Mirae Asset Venture Investment (미래에셋벤처투자)",
                country="KR",
                website="https://www.miraeassetvi.com",
                investment_thesis="Significant healthcare allocation. Interest in digital therapeutics (DTx), health data analytics, and AI-powered clinical solutions.",
                preferred_stages=["Series A", "Series B", "Series C"],
                portfolio_keywords=["Digital Therapeutics", "Health Data", "AI Clinical", "Cross-border"],
                contact_email="venture@miraeasset.com",
            ),
            VCFirm(
                id="vc-spring-009",
                name="SpringCamp (스프링캠프)",
                country="KR",
                website="https://www.springcamp.co",
                investment_thesis="Naver-backed early stage investor. Strong track record in bio-AI convergence and digital health platforms.",
                preferred_stages=["Seed", "Pre-Series A", "Series A"],
                portfolio_keywords=["Bio-AI", "Healthcare SaaS", "Digital Health Platform"],
                contact_email="invest@springcamp.co",
            ),
            VCFirm(
                id="vc-atinum-010",
                name="Atinum Investment (아티넘인베스트먼트)",
                country="KR",
                website="https://www.atinum.com",
                investment_thesis="Technology-driven VC with bio-pharma expertise. Focus on first-in-class drug candidates and biosimilars.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["First-in-class", "Biosimilar", "CDMO", "Pharma"],
                contact_email="bio@atinum.com",
            ),
            VCFirm(
                id="vc-kakao-011",
                name="Kakao Ventures (카카오벤처스)",
                country="KR",
                website="https://www.kakaoventures.co",
                investment_thesis="Early-stage focus on bio-IT convergence, healthcare platforms, and AI-driven diagnostics.",
                preferred_stages=["Seed", "Series A"],
                portfolio_keywords=["Bio-IT", "Platform", "AI Diagnostics"],
                contact_email="invest@kakaoventures.co",
            ),
            VCFirm(
                id="vc-sv-012",
                name="SV Investment (SV인베스트먼트)",
                country="KR",
                website="http://www.svinvestment.com",
                investment_thesis="Specializing in overseas expansion of Korean bio companies. Interested in immunotherapy and gene editing.",
                preferred_stages=["Series A", "Series B", "Growth"],
                portfolio_keywords=["Immunotherapy", "Gene Editing", "Global Expansion"],
                contact_email="sv@svinvestment.com",
            ),
            VCFirm(
                id="vc-daol-013",
                name="Daol Investment (다올인베스트먼트)",
                country="KR",
                website="https://www.daolinvestment.com",
                investment_thesis="Broad interest from traditional pharma to digital health. Long history of successful bio exits.",
                preferred_stages=["Series A", "Series B", "Series C"],
                portfolio_keywords=["Biotech", "Medtech", "Digital Health"],
                contact_email="info@daolinvestment.com",
            ),
            VCFirm(
                id="vc-posco-014",
                name="POSCO Capital (포스코기술투자)",
                country="KR",
                website="https://www.poscocapital.com",
                investment_thesis="CVC focused on bio-materials, diagnostics, and industrial biotech convergence.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Bio-materials", "Diagnostics", "Industrial Biotech"],
                contact_email="poscocapital@posco.com",
            ),
            VCFirm(
                id="vc-samsung-015",
                name="Samsung Venture Investment (삼성벤처투자)",
                country="KR",
                website="https://www.samsungventure.co.kr",
                investment_thesis="Strategic focus on next-gen medical devices, digital health, and platform technologies for Samsung.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Medical Device", "Digital Health", "Platform Tech"],
                contact_email="svic@samsung.com",
            ),
            VCFirm(
                id="vc-shinhan-016",
                name="Shinhan Venture Investment (신한벤처투자)",
                country="KR",
                website="http://www.shinhanventure.com",
                investment_thesis="Part of Shinhan Financial Group. Interest in late-stage clinical biotech and digital health.",
                preferred_stages=["Series B", "Series C", "Growth"],
                portfolio_keywords=["Clinical Biotech", "Digital Health", "Financial Tech"],
                contact_email="venture@shinhan.com",
            ),
            VCFirm(
                id="vc-woori-017",
                name="Woori Venture Partners (우리벤처파트너스)",
                country="KR",
                website="https://www.woorivp.com",
                investment_thesis="Major player in Korean bio scene. Supports companies from early R&D to clinical trials.",
                preferred_stages=["Series A", "Series B", "Series C"],
                portfolio_keywords=["R&D", "Clinical Trials", "Biotech"],
                contact_email="bio@woorivp.com",
            ),
            VCFirm(
                id="vc-smilegate-018",
                name="Smilegate Investment (스마일게이트인베스트먼트)",
                country="KR",
                website="https://www.smilegateinvestment.com",
                investment_thesis="Innovative technologies in healthcare. Interested in AI drug discovery and remote monitoring.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Healthcare", "AI Drug Discovery", "Remote Monitoring"],
                contact_email="invest@smilegate.com",
            ),
            VCFirm(
                id="vc-partners-019",
                name="Partners Investment (파트너스인베스트먼트)",
                country="KR",
                website="http://www.partnersi.co.kr",
                investment_thesis="Focus on oncology and rare diseases. Deep technical due diligence capability.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Oncology", "Rare Disease", "Tech Due Diligence"],
                contact_email="bio@partnersi.co.kr",
            ),
            VCFirm(
                id="vc-imm-020",
                name="IMM Investment (IMM인베스트먼트)",
                country="KR",
                website="https://www.imminvest.com",
                investment_thesis="Growth capital for mature bio companies. Interested in large-scale platform technologies.",
                preferred_stages=["Series B", "Growth", "Pre-IPO"],
                portfolio_keywords=["Growth Capital", "Platform Tech", "Licensing"],
                contact_email="info@imminvest.com",
            ),
            VCFirm(
                id="vc-stic-021",
                name="STIC Investments (스틱인베스트먼트)",
                country="KR",
                website="https://www.stic.re.kr",
                investment_thesis="Focus on buyout and growth in healthcare services and medical devices.",
                preferred_stages=["Growth", "Buyout"],
                portfolio_keywords=["Healthcare Service", "Medtech", "Private Equity"],
                contact_email="info@stic.re.kr",
            ),
            VCFirm(
                id="vc-premier-022",
                name="Premier Partners (프리미어파트너스)",
                country="KR",
                website="http://www.premierpartners.co.kr",
                investment_thesis="Specialist in life sciences. Focus on first-in-class therapeutics and platforms.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["First-in-class", "Platform Tech", "Life Science"],
                contact_email="info@premierpartners.co.kr",
            ),
            VCFirm(
                id="vc-kolon-023",
                name="Kolon Investment (코오롱인베스트먼트)",
                country="KR",
                website="http://www.koloninvestment.com",
                investment_thesis="CVC interested in cell/gene therapy and bio-materials. Early-stage support.",
                preferred_stages=["Seed", "Series A"],
                portfolio_keywords=["Cell Therapy", "Gene Therapy", "Bio-materials"],
                contact_email="invest@kolon.com",
            ),
            VCFirm(
                id="vc-nh-024",
                name="NH Venture Investment (NH벤처투자)",
                country="KR",
                website="https://www.nhventure.co.kr",
                investment_thesis="Agricultural and bio focus. Interested in agtech-bio convergence and diagnostics.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Agtech", "Bio Convergence", "Functional Food"],
                contact_email="nhventure@nh.com",
            ),
            VCFirm(
                id="vc-companyk-025",
                name="Company K Partners (컴퍼니케이파트너스)",
                country="KR",
                website="http://www.companyk.co.kr",
                investment_thesis="Interested in digital healthcare, AI diagnostics, and medical data platforms.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Digital Health", "AI Diagnostics", "Data Platform"],
                contact_email="invest@companyk.co.kr",
            ),
            VCFirm(
                id="vc-capstone-026",
                name="Capstone Partners (캡스톤파트너스)",
                country="KR",
                website="https://www.capstonepartners.co.kr",
                investment_thesis="Early-stage specialist. Interested in bio-IT convergence and digital wellness.",
                preferred_stages=["Seed", "Series A"],
                portfolio_keywords=["Bio-IT", "Digital Wellness", "Early Stage"],
                contact_email="capstone@capstone.co.kr",
            ),
            VCFirm(
                id="vc-bonangels-027",
                name="BonAngels Venture Partners (본엔젤스벤처파트너스)",
                country="KR",
                website="https://bonangels.net",
                investment_thesis="Pre-eminent early-stage investor. Interested in disruptive bio-tech and digital health.",
                preferred_stages=["Seed", "Pre-Series A"],
                portfolio_keywords=["Disruptive Tech", "Biotech", "Digital Health"],
                contact_email="contact@bonangels.net",
            ),
            VCFirm(
                id="vc-ts-028",
                name="TS Investment (TS인베스트먼트)",
                country="KR",
                website="http://www.tsinvestment.co.kr",
                investment_thesis="Focused on M&A and growth in healthcare. Interested in medtech and bio-pharma.",
                preferred_stages=["Series B", "Growth", "M&A"],
                portfolio_keywords=["M&A", "Medtech", "Bio-pharma"],
                contact_email="info@tsinvestment.co.kr",
            ),
            VCFirm(
                id="vc-sbi-029",
                name="SBI Investment Korea (SBI인베스트먼트)",
                country="KR",
                website="https://www.sbiinvestment.co.kr",
                investment_thesis="Global network via SBI Group. Interested in cross-border bio investments.",
                preferred_stages=["Series A", "Series B", "Growth"],
                portfolio_keywords=["Global Network", "Cross-border", "Platform Tech"],
                contact_email="sbi@sbi.co.kr",
            ),
            VCFirm(
                id="vc-utc-030",
                name="UTC Investment (UTC인베스트먼트)",
                country="KR",
                website="http://www.utc.co.kr",
                investment_thesis="Bio-pharma and diagnostics focus. Interested in novel biomarkers and drug candidates.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Biomarker", "Diagnostics", "Drug Candidate"],
                contact_email="utc@utc.co.kr",
            ),
            VCFirm(
                id="vc-solidus-031",
                name="Solidus Investment (솔리더스인베스트먼트)",
                country="KR",
                website="http://www.solidusinvest.com",
                investment_thesis="Bio-specialized VC. Focused on immunotherapy, cell therapy, and medical devices.",
                preferred_stages=["Series A", "Series B", "Series C"],
                portfolio_keywords=["Immunotherapy", "Cell Therapy", "Medtech"],
                contact_email="info@solidusinvest.com",
            ),
            VCFirm(
                id="vc-daily-032",
                name="Daily Venture Capital (데일리파트너스)",
                country="KR",
                website="https://www.dayli.partners",
                investment_thesis="Top bio-specialized VC. Coverage of bio ecosystem from Seed to Pre-IPO.",
                preferred_stages=["Seed", "Series A", "Series B", "Growth"],
                portfolio_keywords=["Bio-specialized", "Healthcare", "Full Lifecycle"],
                contact_email="bio@dayli.partners",
            ),
            VCFirm(
                id="vc-medytox-033",
                name="Medytox Venture Investment (메디톡스벤처투자)",
                country="KR",
                website="http://www.medytoxventure.com",
                investment_thesis="CVC for Medytox. Focused on aesthetics, medtech, and drug discovery.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Aesthetics", "Medtech", "Drug Discovery"],
                contact_email="invest@medytox.com",
            ),
            VCFirm(
                id="vc-ls-034",
                name="L&S Venture Capital (엘앤에스벤처캐피탈)",
                country="KR",
                website="http://www.lnsvc.com",
                investment_thesis="Deep tech and bio-pharma investor. Interested in therapeutic platforms.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Deep Tech", "Bio-pharma", "Diagnostics"],
                contact_email="lns@lnsvc.com",
            ),
            VCFirm(
                id="vc-sl-035",
                name="SL Investment (에스엘인베스트먼트)",
                country="KR",
                website="https://www.slinvestment.com",
                investment_thesis="Experienced bio investor. Interested in healthcare IT and medical infrastructure.",
                preferred_stages=["Series A", "Series B", "Growth"],
                portfolio_keywords=["Healthcare IT", "Med-Infra", "Growth"],
                contact_email="info@slinvestment.com",
            ),
            VCFirm(
                id="vc-bnh-036",
                name="BNH Investment (BNH인베스트먼트)",
                country="KR",
                website="https://www.bnhinvestment.com",
                investment_thesis="Bio-dedicated firm. Focused on novel drug discovery and platform technologies.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Drug Discovery", "Platform Tech", "Healthcare"],
                contact_email="bnh@bnhinvestment.com",
            ),
            VCFirm(
                id="vc-dtn-037",
                name="DTN Investment (DTN인베스트먼트)",
                country="KR",
                website="https://www.dtninvestment.com",
                investment_thesis="Interested in bio-IT convergence and digital healthcare platforms.",
                preferred_stages=["Series A", "Series B"],
                portfolio_keywords=["Bio-IT", "Digital Health", "Tech-driven"],
                contact_email="info@dtninvestment.com",
            ),
            VCFirm(
                id="vc-medypost-038",
                name="Medy-Post (메디포스트)",
                country="KR",
                website="https://www.medi-post.com",
                investment_thesis="CVC focused on regenerative medicine and stem cell therapy.",
                preferred_stages=["Series A", "Strategic"],
                portfolio_keywords=["Regenerative Medicine", "Stem Cell", "Cord Blood"],
                contact_email="invest@medipost.co.kr",
            ),
            VCFirm(
                id="vc-yuhan-039",
                name="Yuhan Corp (유한양행)",
                country="KR",
                website="https://www.yuhan.co.kr",
                investment_thesis="Strategic investor focused on oncology and global licensing.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Oncology", "Metabolism", "Licensing"],
                contact_email="invest@yuhan.co.kr",
            ),
            VCFirm(
                id="vc-gc-040",
                name="GC Biopharma (녹십자)",
                country="KR",
                website="https://www.globalgreencross.com",
                investment_thesis="Strategic focus on vaccines, blood products, and rare diseases.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Vaccine", "Blood Product", "Rare Disease"],
                contact_email="invest@greencross.com",
            ),
            VCFirm(
                id="vc-hanmi-041",
                name="Hanmi Ventures (한미벤쳐스)",
                country="KR",
                website="http://www.hanmiventures.com",
                investment_thesis="CVC for Hanmi Pharma. Focused on metabolic disease and digital therapeutics.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Oncology", "Metabolic Disease", "DTx"],
                contact_email="info@hanmiventures.com",
            ),
            VCFirm(
                id="vc-ckd-042",
                name="CKD Venture Capital (종근당창업투자)",
                country="KR",
                website="http://www.ckdvc.com",
                investment_thesis="CVC for CKD Pharma. Interested in small molecule discovery and medtech.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Small Molecule", "Biosimilar", "Medtech"],
                contact_email="info@ckdvc.com",
            ),
            VCFirm(
                id="vc-daewoong-043",
                name="Daewoong Pharmaceutical (대웅제약)",
                country="KR",
                website="https://www.daewoong.co.kr",
                investment_thesis="Strategic focus on aesthetics and cell/gene therapy platforms.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Aesthetics", "GI", "Cell Therapy"],
                contact_email="invest@daewoong.co.kr",
            ),
            VCFirm(
                id="vc-hugel-044",
                name="Hugel (휴젤)",
                country="KR",
                website="http://www.hugel.co.kr",
                investment_thesis="Focus on medical aesthetics and global expansion.",
                preferred_stages=["Strategic", "Growth"],
                portfolio_keywords=["Aesthetics", "Bio-tech", "Global Expansion"],
                contact_email="ir@hugel.co.kr",
            ),
            VCFirm(
                id="vc-seegene-045",
                name="Seegene (씨젠)",
                country="KR",
                website="http://www.seegene.co.kr",
                investment_thesis="Strategic focus on molecular diagnostics and PCR technology.",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Molecular Diagnostics", "PCR", "Reagent Platform"],
                contact_email="ir@seegene.com",
            ),
            VCFirm(
                id="vc-sdbiosensor-046",
                name="SD Biosensor (에스디바이오센서)",
                country="KR",
                website="https://www.sdbiosensor.com",
                investment_thesis="Focus on rapid diagnostics and point-of-care testing (POCT).",
                preferred_stages=["Series A", "Series B", "Strategic"],
                portfolio_keywords=["Rapid Diagnostics", "POCT", "Platform Tech"],
                contact_email="ir@sdbiosensor.com",
            ),
            VCFirm(
                id="vc-bridge-047",
                name="Bridge Investment (브릿지인베스트먼트)",
                country="KR",
                website="http://www.bridgeinvest.co.kr",
                investment_thesis="Bridging early-stage research to commercial success. Tech-transfer specialist.",
                preferred_stages=["Seed", "Series A"],
                portfolio_keywords=["Tech Transfer", "Lab Spinout", "Early Stage"],
                contact_email="info@bridgeinvest.co.kr",
            ),
            VCFirm(
                id="vc-quad-048",
                name="Quad Investment Management (쿼드자산운용)",
                country="KR",
                website="https://www.quadim.com",
                investment_thesis="Bio-focused asset management. Investing in mid-to-late stage bio companies.",
                preferred_stages=["Series B", "Series C", "Public"],
                portfolio_keywords=["Mid-Late Stage", "Public Market", "Bio Focus"],
                contact_email="info@quadim.com",
            ),
            VCFirm(
                id="vc-timefolio-049",
                name="Timefolio Asset Management (타임폴리오자산운용)",
                country="KR",
                website="https://www.timefolio.co.kr",
                investment_thesis="Significant bio vertical. Focus on clinical-stage biotech and market leaders.",
                preferred_stages=["Series B", "Growth", "Public"],
                portfolio_keywords=["Clinical Biotech", "Market Leader", "Multi-strategy"],
                contact_email="info@timefolio.co.kr",
            ),
            VCFirm(
                id="vc-dsasset-050",
                name="DS Asset Management (DS자산운용)",
                country="KR",
                website="http://www.dsasset.com",
                investment_thesis="Strong focus on pre-IPO bio companies and high-valuation platforms.",
                preferred_stages=["Series C", "Pre-IPO", "Growth"],
                portfolio_keywords=["Pre-IPO", "Platform Tech", "Valuation"],
                contact_email="info@dsasset.com",
            ),
        ]

    def _get_global_bio_vcs(self) -> list[VCFirm]:
        """글로벌 주요 바이오 VC 데이터"""
        return [
            VCFirm(
                id="vc-racap-101",
                name="RA Capital Management",
                country="US",
                website="https://www.racap.com",
                investment_thesis="Evidence-based investing in public and private healthcare. Requires clear biological proof of concept and strong IP. Major focus on mRNA therapeutics, protein degradation, gene editing, and next-gen oncology.",
                preferred_stages=["Series A", "Series B", "Crossover"],
                portfolio_keywords=["mRNA", "Gene Editing", "Protein Degradation", "Oncology"],
                contact_email="deals@racap.com",
            ),
            VCFirm(
                id="vc-orbimed-102",
                name="OrbiMed Advisors",
                country="US",
                website="https://www.orbimed.com",
                investment_thesis="One of the world's largest healthcare-dedicated investment firms. Multi-stage, global portfolio spanning pharmaceuticals, biotechnology, medical devices, and healthcare IT. Over $18B AUM.",
                preferred_stages=["Series A", "Series B", "Growth", "Public"],
                portfolio_keywords=["Global Pharma", "Biotech", "MedTech", "Large Scale"],
                contact_email="info@orbimed.com",
            ),
            VCFirm(
                id="vc-a16zbio-103",
                name="a16z Bio + Health",
                country="US",
                website="https://a16z.com/bio-health",
                investment_thesis="Andreessen Horowitz's dedicated bio fund. Investing in bold founders applying engineering principles to biology. Focus areas: bio-AI platforms, computational drug discovery, synthetic biology, and health tech infrastructure.",
                preferred_stages=["Seed", "Series A", "Series B"],
                portfolio_keywords=["Bio-AI", "Computational Biology", "Synthetic Biology", "Health Tech"],
                contact_email="bio@a16z.com",
            ),
            VCFirm(
                id="vc-sofinnova-104",
                name="Sofinnova Partners",
                country="FR",
                website="https://www.sofinnovapartners.com",
                investment_thesis="Europe's leading life sciences investor with 50+ year history. Deep expertise in rare diseases, oncology, and industrial biotech. Strong connections to European academic research institutions and pharma companies.",
                preferred_stages=["Seed", "Series A", "Series B"],
                portfolio_keywords=["Rare Disease", "Industrial Biotech", "European Pharma"],
                contact_email="info@sofinnova.fr",
            ),
        ]


# Singleton
_vc_crawler: VCCrawler | None = None


def get_vc_crawler() -> VCCrawler:
    global _vc_crawler
    if _vc_crawler is None:
        _vc_crawler = VCCrawler()
    return _vc_crawler
