from __future__ import annotations

import re
import shlex

BROKER_SAFE_SENSOR_ID_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")
DYNSEC_OPTIONS_PLACEHOLDER = "<connection options>"


def is_broker_safe_sensor_id(sensor_id: str) -> bool:
    return bool(BROKER_SAFE_SENSOR_ID_RE.fullmatch(sensor_id.strip()))


def quote_shell(value: str) -> str:
    return shlex.quote(value)


def build_acl_file(sensor_ids: list[str]) -> str:
    lines = [
        "# Generated by AgriGuard from active sensor_devices.",
        "# MQTT username must match sensor_id.",
        "# Disabled or unsupported sensors are intentionally omitted.",
    ]
    for sensor_id in sensor_ids:
        lines.extend(
            [
                "",
                f"user {sensor_id}",
                f"topic write agriguard/sensors/{sensor_id}",
                "topic read agriguard/alerts",
            ]
        )
    return "\n".join(lines) + "\n"


def build_password_file_commands(
    *,
    active_sensor_ids: list[str],
    disabled_sensor_ids: list[str],
    password_file_path: str,
) -> tuple[list[str], list[str]]:
    quoted_path = quote_shell(password_file_path)
    create_or_update = [f"mosquitto_passwd {quoted_path} {quote_shell(sensor_id)}" for sensor_id in active_sensor_ids]
    delete = [f"mosquitto_passwd -D {quoted_path} {quote_shell(sensor_id)}" for sensor_id in disabled_sensor_ids]
    return create_or_update, delete


def build_dynamic_security_commands(
    *,
    active_sensor_ids: list[str],
    disabled_sensor_ids: list[str],
    role_name: str,
) -> list[str]:
    quoted_role = quote_shell(role_name)
    commands = [
        f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec setDefaultACLAccess publishClientSend deny",
        f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec setDefaultACLAccess subscribe deny",
        f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec createRole {quoted_role}",
        (
            f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec addRoleACL "
            f"{quoted_role} publishClientSend 'agriguard/sensors/%u' allow 10"
        ),
        (
            f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec addRoleACL "
            f"{quoted_role} subscribeLiteral agriguard/alerts allow 5"
        ),
        (
            f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec addRoleACL "
            f"{quoted_role} publishClientReceive agriguard/alerts allow 5"
        ),
    ]
    for sensor_id in active_sensor_ids:
        quoted_sensor_id = quote_shell(sensor_id)
        commands.extend(
            [
                f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec createClient {quoted_sensor_id}",
                f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec setClientPassword {quoted_sensor_id}",
                f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec addClientRole {quoted_sensor_id} {quoted_role} 10",
                f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec enableClient {quoted_sensor_id}",
            ]
        )
    for sensor_id in disabled_sensor_ids:
        commands.append(f"mosquitto_ctrl {DYNSEC_OPTIONS_PLACEHOLDER} dynsec disableClient {quote_shell(sensor_id)}")
    return commands
